version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-2:487148038595:task-definition/url-shortener:24"
        LoadBalancerInfo:
          ContainerName: "url-shortener"
          ContainerPort: 8080
