name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      image-uri:
        description: "Image URI from ECR (e.g., 123456789.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:abc123)"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Get latest task definition ARN
        id: get-task-def
        run: |
          export LATEST_ARN=$(aws ecs describe-services \
            --cluster url-short-ecs \
            --services url-shortener-service \
            --query "services[0].taskDefinition" \
            --output text)
          echo "LATEST_ARN=$LATEST_ARN" >> $GITHUB_OUTPUT

      - name: Fetch previous task definition JSON
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ steps.get-task-def.outputs.LATEST_ARN }} \
            --query "taskDefinition" \
            --output json | \
            jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .deregisteredAt)' \
            > old-task-def.json

      - name: Replace image in task definition
        run: |
          jq --arg img "${{ github.event.inputs.image-uri }}" \
            '.containerDefinitions[0].image = $img' old-task-def.json > new-task-def.json

      - name: Register new ECS task definition revision
        id: register-task-def
        run: |
          ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)
          echo "TASK_DEFINITION_ARN=$ARN" >> $GITHUB_OUTPUT
          echo "TASK_DEFINITION_REVISION=$(aws ecs describe-task-definition --task-definition $ARN --query 'taskDefinition.revision' --output text)" >> $GITHUB_OUTPUT

      - name: Update appspec.yml with new task definition
        run: |
          # Update appspec.yml with the new task definition ARN using sed
          sed -i "s|TaskDefinition: \".*\"|TaskDefinition: \"${{ steps.register-task-def.outputs.TASK_DEFINITION_ARN }}\"|g" revisions/appspec.yml
          
          echo "Updated appspec.yml with task definition: ${{ steps.register-task-def.outputs.TASK_DEFINITION_ARN }}"

      - name: Upload appspec.yml to S3
        run: |
          # Upload updated appspec.yml to S3 bucket
          aws s3 cp revisions/appspec.yml s3://url-shortener-codedeploy-revisions/appspec.yml
          echo "Uploaded appspec.yml to S3"

      - name: Create CodeDeploy deployment
        id: deployment
        run: |
          # Create a new deployment
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --application-name url-shortener-codedeploy-app \
            --deployment-group-name url-shortener-dg \
            --s3-location bucket=url-shortener-codedeploy-revisions,key=appspec.yml,bundleType=YAML \
            --region eu-west-2 \
            --query 'deploymentId' \
            --output text)
          
          echo "Deployment ID: $DEPLOYMENT_ID"
          echo "deployment-id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT

      - name: Wait for deployment completion
        run: |
          DEPLOYMENT_ID="${{ steps.deployment.outputs.deployment-id }}"
          echo "Waiting for deployment $DEPLOYMENT_ID to complete..."
          
          # Wait for deployment to complete (with timeout)
          aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID --region eu-west-2
          
          if [ $? -eq 0 ]; then
            echo " Deployment successful!"
          else
            echo "Deployment failed!"
            exit 1
          fi

      - name: Output deployment results
        run: |
          echo "Deployment completed successfully!"
          echo "Image: ${{ github.event.inputs.image-uri }}"
          echo "Task Definition: ${{ steps.create-task-def.outputs.TASK_DEFINITION_ARN }}"
          echo "Deployment ID: ${{ steps.deployment.outputs.deployment-id }}"
          echo ""
          echo "Your application is now running with the new version!"
